name: "tidybeaver-filebeat"
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitorirg.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

filebeat.inputs:
- type: log
  scan_frequency: 1s
  enabled: true
  paths:
  - /logs/*.log
  fields:
  - service: tidybeaver
  fields under root: true
  json:
    keys_under_root: true
    overwrite keys: true
    message_key: 'message'

output.elasticsearch:
  hosts: ["elasticsearch:9200"]