name: "filebeat"
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitorirg.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /logs/output/OutputLogs.json
  parsers:
    - ndjson

output.elasticsearch:
  index: "tidybeaver"
  hosts: ["elasticsearch:9200"]