services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  es-template-setup:
    image: curlimages/curl:latest
    depends_on:
      - elasticsearch
    volumes:
      - ./filebeat/filebeat-index-template.json:/filebeat-index-template.json:ro
    entrypoint: >
      sh -c "
        until curl -s http://elasticsearch:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'; do
          echo 'Waiting for elasticsearch...';
          sleep 5;
        done;
        curl -X PUT http://elasticsearch:9200/_template/filebeat-template -H 'Content-Type: application/json' -d @/filebeat-index-template.json
      "

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.15.0
    container_name: filebeat
    command: filebeat -e --strict.perms=false
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./tidybeaver:/logs/
    depends_on:
      - elasticsearch
      - kibana

  tidybeaver:
    build:
      context: ./tidybeaver
      dockerfile: Dockerfile
    container_name: tidybeaver
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
    volumes:
      - ./tidybeaver:/logs

#  db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_DB: TidyBeaverLogs
#      POSTGRES_USER: tidybeaver
#      POSTGRES_PASSWORD: tidybeaver
#    volumes:
#      - db_data:/var/lib/postgresql/data
#      - ./postgres/initdb:/docker-entrypoint-initdb.d
#    ports: 
#      - "5432:5432"
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
#      interval: 1m
#      timeout: 30s
#      retries: 10

  kibana-setup:
    image: curlimages/curl:latest
    depends_on:
      - kibana
    entrypoint: >
      sh -c "
        until curl -s http://kibana:5601/api/status | grep -q '\"state\":\"green\"'; do
          echo 'Waiting for kibana...';
          sleep 5;
        done;
        curl -X POST http://kibana:5601/api/saved_objects/index-pattern -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -d '{\"attributes\":{\"title\":\"tidybeaver\",\"timeFieldName\":\"@timestamp\"}}'
      "

volumes:
  elasticsearch_data:
    driver: local
#  db_data: 
#    driver: local
