services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  filebeat:
    build:
      context: ./filebeat
    container_name: filebeat
    command: filebeat -e --strict.perms=false
    volumes:
      - ./tidybeaver:/logs
    depends_on:
      - elasticsearch
      - kibana
  tidybeaver:
    build:
      context: ./tidybeaver
      dockerfile: Dockerfile
    container_name: tidybeaver
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
    volumes:
      - ./tidybeaver-logs:/logs
volumes:
  elasticsearch_data:
    driver: local