CREATE TABLE Logs (
    id SERIAL PRIMARY KEY,
    category TEXT,
    category_number INTEGER,
    checksum TEXT,
    client_ip TEXT,
    "column" TEXT,
    component TEXT,
    computer_name TEXT,
    "constraint" TEXT,
    container TEXT,
    correlation_id TEXT,
    data TEXT[], -- Array of text
    datatype TEXT,
    detail TEXT,
    endpoint TEXT,
    entry_type TEXT,
    environment TEXT,
    errcode TEXT,
    event_id TEXT,
    event_type TEXT,
    file_path TEXT,
    file_size BIGINT,
    host TEXT,
    http_method TEXT,
    index INTEGER,
    instance_id INTEGER,
    latency_ms INTEGER,
    level TEXT,
    line_number INTEGER,
    log_name TEXT,
    machine_name TEXT,
    message TEXT,
    request_body TEXT,
    replacement_strings TEXT[], -- Array of text
    response_body TEXT,
    rows_affected INTEGER,
    schema TEXT,
    service TEXT,
    source TEXT,
    split_lines TEXT,
    span_id TEXT,
    status_code INTEGER,
    table_name TEXT,
    time_generated TIMESTAMP,
    time_written TIMESTAMP,
    transaction_id TEXT,
    user_agent TEXT,
    user_id TEXT,
    user_name TEXT,
    query TEXT
);