package config

import (
	json "encoding/json"
	"fmt"
	"os"

	"github.com/joho/godotenv"
)

// TODO
// Refactor to switch from Global variables to arguments
var CFG Configs
var UIC UserInputConfigurations

type Configs struct {
	App struct {
		LogLevel  string `json:"LogLevel"`
		LogAmount string `json:"LogAmount"`
	} `json:"App"`
	WindowsEventLog struct {
		Enabled  bool     `json:"Enabled"`
		Channels []string `json:"Channels"`
		Query    string   `json:"Query"`
	} `json:"WindowsEventLog"`
}

type UserInputConfigurations struct {
	UseFS            bool
	UseDatabase      bool
	UseWindowsEvents bool
	UseAPI           bool
	UseMSVC          bool
	UseMockedLogs    bool
}

func Init() (Configs, UserInputConfigurations) {
	getDefaultConfig()
	getCustomConfig()
	printConfigs()
	return CFG, UIC
}

func getDefaultConfig() {
	configFile, err := os.Open("internal/config/config.json")

	if err != nil {
		panic(`Error getting default configuration for TidyBeaver!!!
		TidyBeaver stopped working.`)
	}

	defer configFile.Close()
	decodedJson := json.NewDecoder(configFile)
	decodedJson.Decode(&CFG)
}

func getCustomConfig() {
	fmt.Println("On this section, you will set which sources for logs you want to use. ")
	fmt.Println("Please, answer the question prompted to you with the letter Y for Yes or N for No ")

	fmt.Println("Do you want to use only logs generated by TidyBeaver? ")
	if !CheckAnswer() {
		fmt.Println("Do you want to use every source available? ")
		if CheckAnswer() {
			UIC.UseAPI = true
			UIC.UseDatabase = true
			UIC.UseFS = true
			UIC.UseMSVC = true
			UIC.UseWindowsEvents = true

		} else if !CheckAnswer() {
			fmt.Println("Answer Y (Yes) or N (No) wether you'd like to use each source bellow:")

			fmt.Println("Local Folder? (C:Logs) ")
			UIC.UseFS = CheckAnswer()

			fmt.Println("TidyBeaver's Postgres Database? ")
			UIC.UseDatabase = CheckAnswer()

			fmt.Println("Windows Events? ")
			UIC.UseWindowsEvents = CheckAnswer()

			fmt.Println("Mocked API? ")
			UIC.UseAPI = CheckAnswer()

			fmt.Println("Mocked Microservice? ")
			UIC.UseMSVC = CheckAnswer()
		}
	} else {
		UIC.UseMockedLogs = true
	}
}

// TODO
// Refactor to take out redundant check
func CheckAnswer() bool {
	userInput := ""
	fmt.Scanln(&userInput)
	for userInput != "Y" && userInput != "N" {
		fmt.Println("Please enter a valid answer: Y for Yes or N for No ")
		fmt.Scanln(&userInput)
	}
	if userInput == "Y" || userInput == "y" {
		return true
	} else if userInput == "N" || userInput == "n" {
		return false
	}
	return false
}

func printConfigs() {

	err := godotenv.Load("T:/Repo/TidyBeaver/.env")
	if err != nil {
		fmt.Println("Error loading .env file")
	}

	// EnvVar, err = godotenv.Read("T:/Repo/TidyBeaver/.env")

	// if err != nil {
	// 	fmt.Println("Error marshalling defaultConfig:", err)
	// 	return
	// }

	fmt.Println("Environment Variables: ")
	fmt.Println(os.Environ())

	defaultConfigsJSON, err := json.MarshalIndent(CFG, "", "  ")

	if err != nil {
		fmt.Println("Error marshalling defaultConfig:", err)
		return
	}

	fmt.Println("Configuration set: ", string(defaultConfigsJSON))
}
