package config

import (
	json "encoding/json"
	"fmt"
	"os"
)

var ConfigValues Configs
var UserInputConfig UserInputConfigurations

type Configs struct {
	App struct {
		Env       string `json:"Env"`
		Port      string `json:"Port"`
		LogLevel  string `json:"LogLevel"`
		LogAmount string `json:"LogAmount"`
	} `json:"App"`
	Database struct {
		Host     string `json:"Host"`
		Port     string `json:"Port"`
		User     string `json:"User"`
		Password string `json:"Password"`
		Name     string `json:"Name"`
		SSLMode  string `json:"SSLMode"`
	} `json:"Database"`
	API struct {
		BaseURL        string `json:"BaseURL"`
		AuthToken      string `json:"AuthToken"`
		TimeoutSeconds string `json:"TimeoutSeconds"`
	} `json:"API"`
	LogPaths struct {
		LocalLogFolder string `json:"LocalLogFolder"`
		IncludeSubDirs bool   `json:"IncludeSubDirs"`
	} `json:"LogPaths"`
	Microservices struct {
		AuthServiceURL    string `json:"AuthServiceURL"`
		PaymentServiceURL string `json:"PaymentService"`
		LogServiceURL     string `json:"LogServiceURL"`
	} `json:"Microservices"`
	WindowsEventLog struct {
		Enabled  bool     `json:"Enabled"`
		Channels []string `json:"Channels"`
		Query    string   `json:"Query"`
	} `json:"WindowsEventLog"`
}

type UserInputConfigurations struct {
	UseFS   bool
	UseDB   bool
	UseWin  bool
	UseAPI  bool
	UseMSVC bool
	UseMock bool
}

func SetConfigs() (Configs, UserInputConfigurations) {
	getDefaultConfig()
	getCustomConfig()
	overwriteConfigs(&UserInputConfig)
	printConfigs()
	return ConfigValues, UserInputConfig
}

func getDefaultConfig() {
	configFile, err := os.Open("internal/config/config.json")
	if err != nil {
		return
	}
	defer configFile.Close()
	decodedJson := json.NewDecoder(configFile)
	decodedJson.Decode(&ConfigValues)
}

func getCustomConfig() {
	fmt.Println("On this section, you will set which sources for logs you want to use. ")
	fmt.Println("Please, answer the question prompted to you with the letter Y for Yes or N for No ")

	fmt.Println("Do you want to use only logs generated by TidyBeaver? ")
	if !checkAnswer() {
		fmt.Println("Do you want to use every source available? ")
		if checkAnswer() {
			UserInputConfig.UseAPI = true
			UserInputConfig.UseDB = true
			UserInputConfig.UseFS = true
			UserInputConfig.UseMSVC = true
			UserInputConfig.UseWin = true

		} else if !checkAnswer() {
			fmt.Println("Do you want to use a Local Folder as a source for logs? ")
			UserInputConfig.UseFS = checkAnswer()

			fmt.Println("Do you want to use a Postgres Database as a source for logs? ")
			UserInputConfig.UseDB = checkAnswer()

			fmt.Println("Do you want to use Windows Events as a source for logs? ")
			UserInputConfig.UseWin = checkAnswer()

			fmt.Println("Do you want to use a mock API as a source for logs? ")
			UserInputConfig.UseAPI = checkAnswer()

			fmt.Println("Do you want to use a mock Microservice as a source for logs? ")
			UserInputConfig.UseMSVC = checkAnswer()
		}
	} else {
		UserInputConfig.UseMock = true
	}
}

func checkAnswer() bool {
	answer := ""
	fmt.Scanln(&answer)
	for answer != "Y" && answer != "N" {
		fmt.Println("Please enter a valid answer: Y for Yes or N for No ")
		fmt.Scanln(&answer)
	}
	if answer == "Y" {
		return true
	} else if answer == "N" {
		return false
	}
	return false
}

func overwriteConfigs(customConfigs *UserInputConfigurations) {
	if !customConfigs.UseFS && !customConfigs.UseMock {
		ConfigValues.LogPaths.IncludeSubDirs = false
		ConfigValues.LogPaths.LocalLogFolder = ""
	}
	if !customConfigs.UseDB || customConfigs.UseMock {
		ConfigValues.Database.Host = ""
		ConfigValues.Database.Name = ""
		ConfigValues.Database.Password = ""
		ConfigValues.Database.Port = ""
		ConfigValues.Database.SSLMode = ""
		ConfigValues.Database.User = ""
	}
	if !customConfigs.UseWin || customConfigs.UseMock {
		ConfigValues.WindowsEventLog.Channels = nil
		ConfigValues.WindowsEventLog.Enabled = false
		ConfigValues.WindowsEventLog.Query = ""
	}
	if !customConfigs.UseAPI || customConfigs.UseMock {
		ConfigValues.API.AuthToken = ""
		ConfigValues.API.BaseURL = ""
		ConfigValues.API.TimeoutSeconds = ""
	}
	if !customConfigs.UseMSVC || customConfigs.UseMock {
		ConfigValues.Microservices.AuthServiceURL = ""
		ConfigValues.Microservices.LogServiceURL = ""
		ConfigValues.Microservices.PaymentServiceURL = ""
	}
}

func printConfigs() {
	env := os.Environ()
	fmt.Println("Environment Variables: ")
	fmt.Println(env)
	defaultConfigJSON, err := json.MarshalIndent(ConfigValues, "", "  ")
	if err != nil {
		fmt.Println("Error marshalling defaultConfig:", err)
		return
	}
	fmt.Println("Configuration set: ", string(defaultConfigJSON))
}
