
docker pull postgres:14.5
	
docker run --name tidybeaverdb -e POSTGRES_USER=tidybeaver POSTGRES_PASSWORD=tidybeaver POSTGRES_DB=TidyBeaverLogs POSTGRES_HOST_AUTH_METHOD=disable -d postgres

docker compose -f [FILE NAME] up